# Generated by Django 2.2.2 on 2019-08-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_east_coordinate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('north_west_coordinate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('south_east_coordinate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('south_west_coordinate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('2Wks', '2 Weeks'), ('1mo', '1 Month'), ('2mo', '2 Months'), ('async', 'Asynchronously')], default='async', max_length=100)),
                ('type_analsis', models.CharField(choices=[('sat', 'Satellite'), ('no2', 'NO2')], default='sat', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagery_viewing.Analysis')),
            ],
        ),
    ]
