# Generated by Django 2.2.2 on 2019-08-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_viewing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='type_analsis',
            new_name='type_analysis',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='north_west_coordinate',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='south_east_coordinate',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='north_east_coordinate',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='south_west_coordinate',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
