# Generated by Django 2.2.2 on 2019-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_viewing', '0002_auto_20190826_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='north_east_coordinate',
            new_name='north_east_lat',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='south_west_coordinate',
            new_name='north_east_long',
        ),
        migrations.AddField(
            model_name='analysis',
            name='south_west_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='south_west_long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
