# Generated by Django 2.2.2 on 2019-08-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_viewing', '0003_auto_20190829_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='north_east_lat',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='north_east_long',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='south_west_lat',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='south_west_long',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
