# Generated by Django 2.2.2 on 2019-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery_viewing', '0004_auto_20190829_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='case',
            field=models.CharField(default='Mongolia', max_length=100),
            preserve_default=False,
        ),
    ]
